### ISSUE TITLE
New Feature: dkajilw on spigot, Stop crafting when container is full

### ISSUE THREAD

**Issue by Apprisco** [Aeltumn/automated_crafting#11]
Feature ideas:

When connected to a hopper, the autocrafter should immediately pull in all items that enter a hopper, just to make it quicker at moving items.
Give us config options to force the autocrafter to craft faster.
Autocrafter should stop crafting when the storage container next to it is full. If there is no storage container, it can still fire.
More redstone features, perhaps even make the autocrafter craft faster with a higher redstone signal, etc.

Thanks for this amazing plugin.

**Comment by Aeltumn** [comment]
> Autocrafter should stop crafting when the storage container next to it is full. If there is no storage container, it can still fire.

This has been implemented in v2.3. 👍

**Comment by Aeltumn** [comment]
It's easier to manage when each suggestion is a separate issue and by now basically all of the suggestions in here have become their own issues, so I'll close this one and keep the others up-to-date.
