### ISSUE TITLE
Crafting items with planks

### ISSUE THREAD

**Issue by HydrA-Smith** [Aeltumn/automated_crafting#13]
It seems like any recipe that can use any type of plank is requiring all types of planks to be in the autocrafter to work. It them uses the appropriate amount of each plank to produce.

This is easily checked with a chest where it requires all the types of planks before producing chests but will consume 8 planks of each type when producing 1 chest

This might also be the cause of why pistons cant be crafted

Im using Spigot 1.16.1

**Comment by Aeltumn** [comment]
Fixed in next update!
