### ISSUE TITLE
Unable to craft suspicious stew

### ISSUE THREAD

**Issue by kriNon** [Aeltumn/automated_crafting#15]
**Describe the bug**
The auto-crafter is unable to craft suspicious stew.

**To Reproduce**
1. Setup an autocrafter
2. Put ingredients for suspicious stew in it.
3. "Autocrafter can't craft this item"

**Expected behavior**
autocrafter crafts suspicious stew.

**Version Information**
What Minecraft/Bukkit version are you running? spigot-1.16.3
What version of Automated Crafting are you using?version 2.3

**Comment by Aeltumn** [comment]
Unfortunately I'm not going to fix this issue for now. Minecraft has a few special recipes that are coded differently. Suspicious stew is one of them. Other examples include fireworks, repairing items and dying armour. These are all recipes that don't show up in the recipe book.
I'm currently not planning on the autocrafters supporting these special recipes, but I'll keep this issue open as I may want to implement it in the future.

**Comment by viabiteroses** [comment]
Hi! Me and a couple friends are playing on our server with this plug-in and love it. I had just built two sugarcane farms and a huge gunpowder farm right next to each other so I could make this huge firework factory for the whole server to take from. The point is, I was very sad to see that this was the case and thought, maybe I could encourage you to look into this issue again. It would be extremely rad. thank you!

**Comment by Aeltumn** [comment]
Suspicious stews and flight duration fireworks should be craftable in the next update.
