### ISSUE TITLE
Dried Kelp Blocks

### ISSUE THREAD

**Issue by Penzz-HM** [Aeltumn/automated_crafting#16]
**Describe the bug**
A Humble Kelp Farmer such as myself only downloaded this to auto-craft dried kelp blocks. But alas, it does not work. It eats the kelp, but does not dispense anything

**To Reproduce**
1. Setup an autocrafter
2. Put 'dried kelp' in it.
3. no dried kelp blocks come out

**Expected behavior**
I just want my dried kelp

**Version Information**
What Minecraft/Bukkit version are you running? spigot 1.16.4
What version of Automated Crafting are you using? 2.3
What versions of dependencies (like CustomCrafting) are being used?

**Additional context**

**Comment by Aeltumn** [comment]
I've found an issue that prevented any items/blocks added in 1.13 or newer from being crafted. It'll be fixed in the next release.
