### ISSUE TITLE
Honey Block Bug

### ISSUE THREAD

**Issue by EdxTheFig** [Aeltumn/automated_crafting#17]
**Describe the bug**
While testing different recipes I wanted to try out if honey bottles will be fully used or will it leave the bottles. When I did the test the bottles were emptied but the honey block was not given.

**To Reproduce**
1. Setup an autocrafter
2. Put honey bottles in it.
3. The honey is used up, but the honey block is made

**Expected behavior**
The Bottles are being emptied and a Honey Block is suppose to be the output

**Version Information**
MC Version:
Paper 1.16.4 (Paper Build 288)

**Comment by Aeltumn** [comment]
I've found an issue that prevented any items/blocks added in 1.13 or newer from being crafted. It'll be fixed in the next release.
