### ISSUE TITLE
Recipes with multiple items in 1 slot aren't supported

### ISSUE THREAD

**Issue by ghost** [Aeltumn/automated_crafting#18]
1. Setup an autocrafter
2. Setup a custom recipe with more than 1 item in 1 slot, using CustomCrafting by WolfyScript
3. Try to autocraft it

The autocrafter should take the right amount of items. If I had an item that takes 16 repeaters to craft, 8 in each slot, an autocrafter would only take two.

Running 1.16.4, paper-261
Automated Crafting 2.4
CustomCrafting 1.6.4.0
Wolfyutilities 1.6.2.14

https://streamable.com/9mt53j

**Comment by Aeltumn** [comment]
This should be supported in the next update.
