### ISSUE TITLE
Lacks support for firework rockets, especially the flight time 1 ones used for flight.

### ISSUE THREAD

**Issue by Apprisco** [Aeltumn/automated_crafting#19]
Extremely simple recipe, 1 gunpowder and 1 paper. Autocrafter simply says, it cannot craft this item.

**Comment by Aeltumn** [comment]
Currently special crafting recipes are not supported. The recipe for a firework rocket is one of those.
I'll consider adding support for the special recipes in the future but as it requires custom code for each special recipe it's not ideal.

**Comment by Aeltumn** [comment]
Firework rockets with only flight duration and no firework stars should be craftable in the next update.
