### ISSUE TITLE
Scaffolding is under-produced

### ISSUE THREAD

**Issue by viabiteroses** [Aeltumn/automated_crafting#20]
**Describe the bug**
when inputting 6 bamboo and 1 string into an autocrafter, it consumes the items, then produces a single scaffold instead of 6

**To Reproduce**
1. Setup an autocrafter
2. Put 'Scaffolding' in it.
3. 'Receive 1 scaffold for the price of 6'

**Expected behavior**
The autocrafter should produce 6 scaffolding per recipe, as it does through a crafting table.

**Version Information**
1.16.5

**Comment by Aeltumn** [comment]
What an odd bug. Crafting wood into planks correctly creates 4 planks. Odd that scaffolding wouldn't work.

**Comment by viabiteroses** [comment]
Is there a simple fix to this? this bug causes my scaffolding farm/factory to be 6x less effective than it could be :(

**Comment by Aeltumn** [comment]
I cannot replicate the issue on the latest version, for me it creates 6 scaffolding for a single craft. Are you running server software that is not spigot/paper?
