### ISSUE TITLE
Issue with Purpur (Possibly?)

### ISSUE THREAD

**Issue by Munchkinnibbler** [Aeltumn/automated_crafting#21]
Basically, I was having issues with the spigot download, having tried the version on here it works great! Please could the spigot website download be updated though so others don't fall for the same issue?

**Comment by Aeltumn** [comment]
I'm not having any issues downloading the jar from [spigotmc.org](https://www.spigotmc.org/resources/automated-crafting.70432/) myself?

**Comment by Munchkinnibbler** [comment]
It seems to be an issue with [Purpur](https://purpur.pl3x.net/), I'm not sure if you're aware of it but its an eventual fork of bukkit. On Purpur it seems highly liable to break and often ends up in no items being autocrafted. Essentially, all items give you the 'this item cannot be autocrafted' message.

**Comment by Aeltumn** [comment]
That is very weird, however that is an issue with Purpur. I only depend on Bukkit giving me an accurate list of all recipes, if Purpur breaks that behaviour it's a problem on their side.
