### ISSUE TITLE
Allow customising where leftover items from crafts end up

### ISSUE THREAD

**Issue by tcaivano** [Aeltumn/automated_crafting#22]
**Is your feature request related to a problem? Please describe.**
When crafting a recipe that leaves behind items (for example, Honey Bottles into Honey Blocks leaves behind glass bottles), the leftover items accumulate in the Auto Crafter.

**Describe the solution you'd like**
I'd like to set up an item filter below the Auto Crafter to remove the leftover items. Currently, hoppers cannot take items from Auto Crafters

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by tcaivano** [comment]
Sorry, submitted before I actually wrote out the feature request. Reopening.

**Comment by Aeltumn** [comment]
In the next update all leftover items will be pushed into the output container (or dropped).
