### ISSUE TITLE
Possible bug with shulker boxes and BlockEntityTag NBT data

### ISSUE THREAD

**Issue by LcorpOfficial** [Aeltumn/automated_crafting#24]
**Describe the bug**
if a shulker is placed, it gains a BlockEntityTag called Items (related to it's containter properties) and cannot be autocrafted. I would suggest adding support for the tag but only for empty shulkers. when I use DumpItem to get it's data; the tag is: `{BlockEntityTag: {Items: []}}`
**To Reproduce**
1. Setup an autocrafter
2. make a shulker box. notice it has no NBT tag
3. place box on ground and pick it up. notice it has a tag for it's container properties.
4. place shulker in autocrafter
5. notice it does not work.

**Expected behavior**
I expect an empty shulker to be accepted in the autocrafter
**Screenshots**
![image](https://user-images.githubusercontent.com/73314328/122780107-84292a00-d27c-11eb-9ab7-563567fe68d8.png)
![image](https://user-images.githubusercontent.com/73314328/122780132-8be8ce80-d27c-11eb-9f3f-19f4831e269e.png)
![image](https://user-images.githubusercontent.com/73314328/122780206-a1f68f00-d27c-11eb-8f79-ae6535a9ade9.png)
![image](https://user-images.githubusercontent.com/73314328/122780257-ade25100-d27c-11eb-989b-e0d2acf83567.png)

**Version Information**
What Minecraft/Bukkit version are you running?
This server is running Airplane version git-Airplane-"a13c511" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
What version of Automated Crafting are you using?
2.4
What versions of dependencies (like CustomCrafting) are being used?
CustomCrafting is not involved in this possible bug, but I do have ShulkerPacks 1.5.12 installed and I'm not sure if it changes the way shulkers behave.
**Additional context**
none at this time

**Comment by Aeltumn** [comment]
Should be fixed in the next update.
