### ISSUE TITLE
Adding Alternate Blocks As Autocrafters

### ISSUE THREAD

**Issue by EpicDude1238** [Aeltumn/automated_crafting#27]
I am currently trying to edit the config.yml to add chests as autocrafters, but cannot figure out what format I need to add them. Help would be appreciated thanks! :)

**Comment by Aeltumn** [comment]
Unfortunately that's not possible, only droppers and dispensers can be autocrafters right now. But I'll mark this down as a possible feature to add in the future.

**Comment by Aeltumn** [comment]
I've added a configuration option for this in the new update.
