### ISSUE TITLE
Blocking Crafted blocks *Custom Reciped Items*

### ISSUE THREAD

**Issue by fahlur** [Aeltumn/automated_crafting#28]
**Is your feature request related to a problem? Please describe.**
A way to make it so specific custom items cant be crafted

**Describe the solution you'd like**
unsure maybe a command to add item to the blacklist while holding set item?

**Describe alternatives you've considered**
Perhaps a material "Whitelist" ?

**Additional context**
Having custom items that are crafted. I dont think some servers would want certain custom items autocrafted. Such as on my server with death return scrolls or waystones. Etc.

**Comment by Aeltumn** [comment]
There is already a configuration option where you can disable certain materials from being crafted.
