### ISSUE TITLE
Glow Item Frames

### ISSUE THREAD

**Issue by fahlur** [Aeltumn/automated_crafting#29]
**Is your feature request related to a problem? Please describe.**
Make it so it works with glowing item frames as well?
It doesnt seem to work with those...

**Describe the solution you'd like**
Add glowing item frame to the check with item frame

**Describe alternatives you've considered**
none..

**Additional context**
Just be a neat idea to add it as a thing since well glow item frames are a thing.

**Comment by Aeltumn** [comment]
Should be fixed in the next update!
