### ISSUE TITLE
Bottles from Honey Block craft produce extra bottles in the output

### ISSUE THREAD

**Issue by TrashCaster** [Aeltumn/automated_crafting#32]
**Describe the bug**
When you setup the autocrafter to craft Honey Blocks, putting in your bottles, and activating it puts out the 4 bottles + 3 extra.

**To Reproduce**
1. Setup an autocrafter
2. Put Honey Block in the item frame.
3. Put honey bottles into the crafter
4. Craft

**Expected behavior**
It is supposed to only output the 4 bottles you put in

**Screenshots**
N/A

**Version Information**
What Minecraft/Bukkit version are you running? 1.18.1, CraftBukkit 1.18.1 #3395 (I recompiled the source code and replaced the spigot Action Bar calls with a console command for /title to make it work on regular Bukkit)
What version of Automated Crafting are you using? 2.6
What versions of dependencies (like CustomCrafting) are being used? Not being used

**Additional context**
I have tested this with 4 bottles producing 7, and more in the stack still outputting 7 per craft.
I have enabled the Redstone-based crafting, so that the tick crafting isn't used. I do wonder if this is still being crafted twice this way though (but i would think it produces 8 bottles then). It's honestly hard to tell.

**Comment by TrashCaster** [comment]
Something to add after some testing, it only outputs extra items when the chest does not contain glass bottles already. If it already has the bottles, it does not dupe the bottles and just adds the 4 it is meant to

**Comment by LilianLem** [comment]
Can confirm that. We also have the problem with the craft of cakes, which spawns two extra empty buckets in the chest.

**Comment by Aeltumn** [comment]
Sorry for the late reaction to this. The bug has been fixed in the new 2.6.1 update.
