### ISSUE TITLE
Autocrafter is only taking one dried kelp to make a kelp block

### ISSUE THREAD

**Issue by EmpathyHeals** [Aeltumn/automated_crafting#5]
Hi, a player just contacted me saying: "hey emp do you know anything about autocrafters only using one kelp to make kelp block bc thats whats happening to me my autocrafter is only taking one dried kelp to make a kelp block." I just updated the plugin but it was the exact same size and name so I think I already had the most updated one on the server.

**Comment by Aeltumn** [comment]
Thanks for reporting this issue, I've fixed it and it will be included in the next release.

**Comment by Thomrl** [comment]
Is this fixed for all kinds of items? I'm asking because I've found 1 oak_log only gives 1 oak_plank

**Comment by Aeltumn** [comment]
Hmm, that sounds like another bug the other way around, that the crafted item will only be of size 1. Can you test if it goes for all recipes with 2 or more items as output (planks, stone bricks, doors) that the autocrafter drops only a single item? If that is the case, could you make a new issue? I'll try to test it too as soon as I've got some time for it.

**Comment by Thomrl** [comment]
I've made a new issue kinda related. But I'm gonna adress the topic I started here again. By itself autocrafter doesnt do anything with logs, but I tried to add it as a custom recipe. It started out working perfectly, it could make 4 planks from 1 log as I specified in the recipe, but when it reach 1 stack in the output chest it started making only 1 plank per log. It could be bypassed by adding another chest under the output chest.

**Comment by Aeltumn** [comment]
So, when not using any custom recipes at all, when you put a plank into the output slot and logs into the dropper nothing happens? What version are you on?

**Comment by Thomrl** [comment]
Exactly. Client: Minecraft 1.14.4 - Server: Paper-235

**Comment by Aeltumn** [comment]
Fixed in next update!
