### ISSUE TITLE
Feature Request: Allow other containers to work as an autocrafter

### ISSUE THREAD

**Issue by mattirizarry** [Aeltumn/automated_crafting#7]
## Description

As a user of this plugin, I would like a hopper, for instance, to be able to craft simpler things such as a block of a resource (iron, diamond, etc.).

### Benefits

This would benefit lots of users, and myself because I have an automated sorting system that would greatly benefit from automatically storing ingots into blocks.

**Comment by Aeltumn** [comment]
Are you aware that autocrafters can input items straight into adjacent containers in front of the dropper? So you could already do this where you could have a hopper put iron ingots into a dropper and have the dropper face into another hopper.

**Comment by mattirizarry** [comment]
Yes I am aware that is a solution. However, in a sorting system where a hopper goes directly in a chest with little wiggle room, it would be very convenient to have a hopper that crafts it and adds it to a chest.

**Comment by Aeltumn** [comment]
> 
> 
> Yes I am aware that is a solution. However, in a sorting system where a hopper goes directly in a chest with little wiggle room, it would be very convenient to have a hopper that crafts it and adds it to a chest.

Hmmm, I think that'd be a bit too unnecessarily convienient. The plugin is already powerful and inexpensive. Don't you have at least 2 blocks of room behind the chests? You could put the dropper adjacent to the chest and have the hopper behind it. And if the chests aren't stacked on top of each other even 1 block of room would suffice.

**Comment by mattirizarry** [comment]
Hey, it's cool. If I get around to it, I'll make the feature my self and open a PR for it. If you want to leave this issue open you can, but if you'd rather move on from it feel free to close it. I figured out my own in-game solution with hoppers anyways. 

This would still be cool tho 👍 

Have a good one my man!

**Comment by Aeltumn** [comment]
The feature shouldn't be too hard to add. I don't think I want it as default behaviour but I'll probably add a configuration file in the next update, maybe I'll add this as an optional setting too then.

**Comment by Aeltumn** [comment]
I've now added this as a configuration option in the upcoming update.
