### ISSUE TITLE
Items that's accepted but nothing happens

### ISSUE THREAD

**Issue by Thomrl** [Aeltumn/automated_crafting#8]
Autocrafter has certain things that it says is accepted, but nothing happens.
**Currently tested**
Works: wooden stairs, bow, spruce wood button, ladder
Doesnt work: sticks, torches, logs to planks, chest

**Comment by Aeltumn** [comment]
What minecraft version are you using?

**Comment by Thomrl** [comment]
Minecraft 1.14.4 - Server Runs Paper-235

**Comment by Tab-160** [comment]
Still a bug, my issue is with droppers. Currently running 1.14.4
![image](https://user-images.githubusercontent.com/43759848/73588031-8ff23180-4478-11ea-872f-0250aea080b1.png)

![image](https://user-images.githubusercontent.com/43759848/73588028-88cb2380-4478-11ea-86b2-af107c4825a9.png)
.

**Comment by Aeltumn** [comment]
> 
> 
> Still a bug, my issue is with droppers. Currently running 1.14.4
> .

I'll have a look at this issue for the next update, thanks for reporting it!

**Comment by Aeltumn** [comment]
Fixed in next update!
